<?php

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Add shop' => 'Добавить магазин',
    'Address' => 'Адрес',
    'After 10 seconds, it ended' => 'Спустя 10 секунд завершилось',
    'An error has occurred: {message}' => 'Произошла ошибка: {message}',
    'Are you sure you want to delete the shop?' => 'Вы уверены, что хотите удалить магазин?',
    'Back' => 'Назад',
    'Change' => 'Изменение',
    'Connection {connResourseId} has disconnected' => 'Соединение {connResourseId} отключилось',
    'Creating a new shop' => 'Создание нового магазина',
    'Data' => 'Данные',
    'Date of creation' => 'Дата создания',
    'Delete' => 'Удалить',
    'Device' => 'Устройство',
    'Device not found' => 'Устройство не найдено',
    'Device with mac: {mac} and the sensor {id} it has been created' => 'Устройство с mac: {mac} и датчиком {id} было создано',
    'Editing' => 'Редактирование',
    'Exception ' => 'Исключение',
    'ID' => 'ID',
    'Mac - address' => 'Мак-адрес',
    'Name of the WIFI network' => 'Имя сети WIFI',
    'New connection' => 'Новое соединение',
    'No value' => 'Нет значения',
    'Range' => 'Диапазон',
    'Save' => 'Сохранить',
    'Send data' => 'Отправить данные',
    'Sending data' => 'Отправка данных',
    'Sensor ID' => 'ID устройства',
    'Sensor token' => 'Токен устройства',
    'Settings file' => 'Файл настроек',
    'Shop' => 'Магазин',
    'Shop address' => 'Адрес магазина',
    'Shop name' => 'Имя магазина',
    'Shop not found' => 'Магазин не найден',
    'Shops' => 'Магазины',
    'The requested page was not found' => 'Запрошенная страница не была найдена',
    'There is no data' => 'Данных нет',
    'Time' => 'Время',
    'To change' => 'Изменить',
    'Token' => 'Токен',
    'Value' => 'Значение',
    'Wifi password' => 'Пароль WIFI',
    'Home' => 'Домой',
];
